# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: go-test
        name: Run Go Tests
        entry: go test ./...
        language: golang
        types: [go]
      - id: go-lint
        name: Run Go Lint
        entry: golangci-lint run
        language: golang
        types: [go]